Add sort command
AY2021S1-CS2103T-W10-4/tp pull request #66
Opened 2020-10-05 19:27 UTC by bangyiwu

First implementation of sorting, sort 1 allows sorting by name, sort 2 allows sorting by address and sort 3 allows sorting by the person's first tag

2020-10-05 19:34 UTC, bangyiwu commented
I will fix the cli fails before reopening

2020-10-07 04:39 UTC, LinkedInk commented
Model should not handle the sortPerson of the addressbook. Should consider moving the function into the excute part of SortCommand and the class in general. Model class has getAddressBook and setAddressBook to help with that.

2020-10-07 09:54 UTC, chan-j-d commented
Is the sort method supposed to sort the current shown list? Or is it supposed to sort the full list of contacts before showing it? Because the former would be much easier to implement and I believe is what we intended to do originally? There is the `model.getFilteredPersonList()` method which gives the last shown list.

Also, I agree with the Hendey's comment about the sortPerson method. I do not think that all the model classes need to have such a method.

2020-10-12 16:24 UTC, bangyiwu commented
Challenges faced: so far only able to sort the address book permanently, if anyone has an idea on how we can sort the address book temporarily, let me know

2020-10-13 17:35 UTC, chan-j-d requested changes
Please take a look at the suggestions

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_SORT = new Prefix("s/");
Is the prefix necessary at all?

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/logic/parser/SortCommandParser.java
> +            index = ParserUtil.parseIndex(argMultimap.getPreamble());
Should be able to obtain the index directly similar to the Delete command for example

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/logic/commands/SortCommand.java
> +            + "4 will be sort by alphabetical order of their first tag\n"
This seems to be outdated compared to what is actually implemented

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/logic/commands/SortCommand.java
> +
Would be nice to have a brief Javadocs description of the class

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/logic/parser/SortCommandParser.java
> + * Parses input arguments and creates a new {@code RemarkCommand} object
This Javadocs is outdated

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
Should probably remove this as it is not used at all

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/Model.java
> +    void sortPerson(Index index);
Should remove this from the interface and the implementing classes

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/person/UniquePersonList.java
> +    }
Should probably remove this as it is only used by the unused sortPersons method in AddressBook

2020-10-13 17:35 UTC, chan-j-d commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +        }
Should probably remove this as it is not used at all

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/ModelManager.java
> +    public void sortPerson(Index index) {
This method should probably take in a Comparator instead in line with how the `updateFilteredPersonList` method works. Model Manager shouldn't need to know exactly which Comparators it needs

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/ModelManager.java
> +        };
The three comparators should probably declared as static constants within the `SortCommand` class itself?

2020-10-13 17:35 UTC, chan-j-d commented on src/main/java/seedu/address/model/ModelManager.java
> +        }
This should probably be done in the SortCommand class itself. `execute` chooses the appropriate Comparator in the execute command to pass to `ModelManager`.

2020-10-14 01:54 UTC, chan-j-d approved these changes
LGTM!

2020-10-14 01:54 UTC, merged