Add editEvent feature
AY2021S1-CS2103T-W10-4/tp pull request #94
Opened 2020-10-13 15:28 UTC by LinkedInk

Related java docs have been corrected along the way.

2020-10-13 16:14 UTC, fyshhh requested changes
code is good, just some minor grammatical errors to fix.

2020-10-13 16:14 UTC, fyshhh commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> + * unique in terms of identity in the UniqueEventList. However, the removal of a event uses Event#equals(Event) so
should be "an" instead of "a" event.

2020-10-13 16:14 UTC, fyshhh commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> +     * Adds a event to the list.
should be "an" instead of "a" event.

2020-10-13 16:19 UTC, LinkedInk commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> + * unique in terms of identity in the UniqueEventList. However, the removal of a event uses Event#equals(Event) so
Fixed

2020-10-13 16:20 UTC, LinkedInk commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> +     * Adds a event to the list.
Fixed

2020-10-14 02:44 UTC, fyshhh approved these changes
lgtm!

2020-10-14 02:52 UTC, fyshhh commented
i think you have to rebase your commits on the most recent upstream/master before you merge because the new PR got merged really late. for the files with merge conflicts i think @chan-j-d removed some methods, he can clarify which to delete.

2020-10-14 02:56 UTC, chan-j-d commented
Please settle the merge conflicts by including both methods for the two different conflicts. Then it'll be good to merge. Thanks!

2020-10-14 03:10 UTC, merged